apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/app: app-test
    application.deploy.reform/tags: test-test
  creationTimestamp: null
  name: wizard-harris
  namespace: vela-system
spec:
  components:
  - name: wizard-harris-web-wizard-web-web
    properties:
      domain: https://google.com
      path: "1"
      resource: High
      secure: false
    type: web-wizard-web
status: {}
