apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: c280c1a2cfcd8abeddfab3ebf35a0f39109fe2de
    application.deploy.reform/deploymentNo: harrisrecover-local_DP1
    application.deploy.reform/environment: local
    application.deploy.reform/name: harrisrecover
    application.deploy.reform/repository: https://github.com/Gglayolun/devhar-not-auto.git
    application.deploy.reform/repositoryPath: "1"
    application.deploy.reform/revision: 2023.04.1
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 6b5c82cf8fbd6720e41370072c0193f4158e3f6c
  creationTimestamp: null
  name: harrisrecover
  namespace: vela-app
spec:
  components:
  - name: harrisrecover-harrisrecover-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 100Mi
      ports:
      - expose: true
        name: http
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
